// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: system/auth.proto

package system

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListAuthResourcesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListAuthResourcesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAuthResourcesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAuthResourcesRequestMultiError, or nil if none found.
func (m *ListAuthResourcesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAuthResourcesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PageSize

	// no validation rules for PageToken

	// no validation rules for Current

	// no validation rules for NoPaging

	if len(errors) > 0 {
		return ListAuthResourcesRequestMultiError(errors)
	}

	return nil
}

// ListAuthResourcesRequestMultiError is an error wrapping multiple validation
// errors returned by ListAuthResourcesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListAuthResourcesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAuthResourcesRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAuthResourcesRequestMultiError) AllErrors() []error { return m }

// ListAuthResourcesRequestValidationError is the validation error returned by
// ListAuthResourcesRequest.Validate if the designated constraints aren't met.
type ListAuthResourcesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAuthResourcesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAuthResourcesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAuthResourcesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAuthResourcesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAuthResourcesRequestValidationError) ErrorName() string {
	return "ListAuthResourcesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListAuthResourcesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAuthResourcesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAuthResourcesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAuthResourcesRequestValidationError{}

// Validate checks the field values on ListAuthResourcesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListAuthResourcesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAuthResourcesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAuthResourcesResponseMultiError, or nil if none found.
func (m *ListAuthResourcesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAuthResourcesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetResources() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListAuthResourcesResponseValidationError{
						field:  fmt.Sprintf("Resources[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListAuthResourcesResponseValidationError{
						field:  fmt.Sprintf("Resources[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListAuthResourcesResponseValidationError{
					field:  fmt.Sprintf("Resources[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TotalSize

	if len(errors) > 0 {
		return ListAuthResourcesResponseMultiError(errors)
	}

	return nil
}

// ListAuthResourcesResponseMultiError is an error wrapping multiple validation
// errors returned by ListAuthResourcesResponse.ValidateAll() if the
// designated constraints aren't met.
type ListAuthResourcesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAuthResourcesResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAuthResourcesResponseMultiError) AllErrors() []error { return m }

// ListAuthResourcesResponseValidationError is the validation error returned by
// ListAuthResourcesResponse.Validate if the designated constraints aren't met.
type ListAuthResourcesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAuthResourcesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAuthResourcesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAuthResourcesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAuthResourcesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAuthResourcesResponseValidationError) ErrorName() string {
	return "ListAuthResourcesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListAuthResourcesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAuthResourcesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAuthResourcesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAuthResourcesResponseValidationError{}
